### ISSUE TITLE
API key is invalid

### ISSUE THREAD

**Issue by dinakarankec** [USDepartmentofLabor/Developer#106]
@MikePulsiferDOL @Supreet7 @supreetkohli 
I generated a access key from https://devtools.dol.gov/developer after signing up, lets say "API_TOKEN". I accessed the inspection information from through curl command with the following command. But still i'm getting the invalid API key. How to resolve this. 

`curl -H "X-API-KEY: API_TOKEN" https://data.dol.gov/get/inspection/limit/5`

**Comment by giridhar** [comment]
@dina-ideas2it I have just tested and I see the data requested 

> [
    {
        "activity_nr": "340961200",
        "reporting_id": "0257220",
        "state_flag": null,
        "estab_name": "PARTY LINE INC",
        "site_address": "CARR 1 KM 28.6BO RIO CANAS",
        "site_city": "CAGUAS",
        "site_state": "PR",
        "site_zip": "00725",
        "owner_type": "A",
        "owner_code": null,
        "adv_notice": "N",
        "safety_hlth": "S",
        "sic_code": null,
        "naics_code": "532310",
        "insp_type": "C",
        "insp_scope": "B",
        "why_no_insp": "I",
        "union_status": "B",
        "safety_manuf": null,
        "safety_const": null,
        "safety_marit": null,
        "health_manuf": null,
        "health_const": null,
        "health_marit": null,
        "migrant": null,
        "mail_street": "HC 05 BOX 57600BO RIO CANAS",
        "mail_city": "CAGUAS",
        "mail_state": "PR",
        "mail_zip": "00725",
        "host_est_key": "HOST_EST_KEY_VALUE",
        "open_date": "2015-09-09",
        "case_mod_date": "2017-08-08",
        "close_conf_date": "2015-10-14",
        "close_case_date": "2015-12-08",
        "ld_dt": "2017-08-09 04:03:57.88329"
    }
>]

Can you please give us more information ?

**Comment by matthenry87** [comment]
I am also experiencing this problem. When I navigate to the following URL:

https://data.dol.gov/get/publications_view?KEY=[KEY HERE]

I get:

{
    "status": "",
    "error": "Invalid API Key "
}

I even tried generating a new Key/Token and am getting the same result.

**Comment by giridhar** [comment]
@matthenry87 whats the email used to generate API key ? I can look up and see why you are getting an invalid key.

**Comment by matthenry87** [comment]
I was just able to make it work using Postman. I had to move the API key into a request header of type 'x-api-key.

Initially hitting the URL https://data.dol.gov/get/publications_view resulted in:
{
    "status": "0",
    "error": "Not Acceptable. Limit must be numeric. Error:406"
}
instead of returning the first 100 as outlined in your documentation.

It does return data when I hit https://data.dol.gov/get/publications_view/limit/100 with the correct request header.

However, it appears that State Minimum Wage data is not available via this API, it seems to only provide information about publications and documents. Is there not a DOL API that will tell me the State Minimum Wage for each state?

**Comment by giridhar** [comment]
@matthenry87 Let me check and get back to you.

**Comment by RobertPRanney** [comment]
I am having the same issue as described here, is there any update on this?

**Comment by giridhar** [comment]
We have sent a request to the concerned agency if they can publish the State Minimum Wage data.

**Comment by giridhar** [comment]
Agency responded and the data is maintained on this website. https://www.dol.gov/whd/minwage/america.htm

**Comment by matthenry87** [comment]
Ah, so you're saying that you don't plan to provide State Minimum Wage data programmatically via an API?

**Comment by giridhar** [comment]
NO. We just started discussions and will move this to the API as soon as possible.

**Comment by bkingo** [comment]
@giridhar Is minimum wage data available via the API at this current time now?
