### ISSUE TITLE
API v2: Invalid API Key 

### ISSUE THREAD

**Issue by gokulanath** [USDepartmentofLabor/Developer#107]
Getting invalid API key response when using PHP SDK, curl operation and POSTMAN
```

//APIv2-Quarry
$context = new GOVDataContext('https://data.dol.gov','MY API KEY','My Secret');

//Instantiate  new request object. Pass the context that contains all the API key info
$request = new GOVDataRequest($context);
$method = NULL;
$arguments = NULL;

if($context->apiURL == 'V1'){

	//APIv1 you want to fetch data from.
	$method = "DOLAgency/Agencies";

	//Build Array arguments
	//Example to skip 1 record and retrieve top 10 records and just get one field.
	$arguments =  Array('format' => '\'json\'','top' => '10','skipCount' => '1');

```

RESPONSE:
```
Array
(
    [0] => {
    "status": false,
    "error": "Invalid API Key "
}
)
```

Note: The same key is working for http://api.dol.gov/V1/DOLAgency/Agencies

For v2 is there any other way to generate API key or same place https://devtools.dol.gov/developer/Tokens/Details/ and also i didn't received any API token email, i just copied it from developers details page.

If you have any working example please post it.

@MikePulsiferDOL @Supreet7 @neilneyman

**Comment by giridhar** [comment]
@gokulanath I have re-sent your api key.

**Comment by gokulanath** [comment]
@giridhar Thanks for your time to look in to the issues.
