### ISSUE TITLE
Dataset & SDK page mockups

### ISSUE THREAD

**Issue by waltcerna** [USDepartmentofLabor/Developer#11]
Dataset detail tab pages and SDK page edits
![datasetdetails4](https://cloud.githubusercontent.com/assets/1934400/5519702/fc2e9ecc-892c-11e4-9b07-ca267dbfce32.jpg)

![datasetdetails_samples](https://cloud.githubusercontent.com/assets/1934400/5519701/fc2dc74a-892c-11e4-9567-ecaa584a0703.jpg)

![sdk_details2](https://cloud.githubusercontent.com/assets/1934400/5519703/fc2f3724-892c-11e4-8d10-b8bdc43596d0.jpg)

**Comment by waltcerna** [comment]
@spoonstein Here is the menu normal / rollover / down / active states (In that order)
![rollover_states](https://cloud.githubusercontent.com/assets/1934400/5598437/56ca8ec6-9284-11e4-94d1-e93081c69bda.jpg)

Here are the Details, Samples and SDK page with the new menu
![datasetdetails5](https://cloud.githubusercontent.com/assets/1934400/5598703/cb806214-9288-11e4-9861-d9500f3dcd20.jpg)

![datasetdetails_samples2](https://cloud.githubusercontent.com/assets/1934400/5598702/cb7d67e4-9288-11e4-92a8-8a2c51ad0260.jpg)

![sdk_details3](https://cloud.githubusercontent.com/assets/1934400/5598704/cb83c2b0-9288-11e4-9e3f-919b92860ad7.jpg)

**Comment by MikePulsiferDOL** [comment]
Something worth looking into to see if it's accessible: https://help.github.com/articles/about-gists/

**Comment by jfc3-dol** [comment]
Is the dataset documentation comp and the samples comp going to be the sample except for the paragraph of text and the two drop down lists?

jfc iii

**Comment by jfc3-dol** [comment]
On the dataset documentation comp, we need to rework the sentence that has the link as "HERE". Screen reader users will read that out of context and not understand what it is about.

jfc iii

**Comment by jfc3-dol** [comment]
If we're going to show the link contents on hover or keyboard focus we, will have to make sure the color contrast is good and text is easy to read.

jfc iii

**Comment by jfc3-dol** [comment]
I recommend we use the keyboard and screen reader accessible left-side secondary navigation that Shirley and I created for the new DOL secondary pages.

Ask me for the link if you want to see what I'm talking about.

jfc iii

**Comment by jfc3-dol** [comment]
On the dataset documentation comp, I think we need to improve the layout/schema of the information so it's easier to read. My suggestion would be to make the text larger and add a bit of padding around it, so the rows don't blend together.

jfc iii

**Comment by jfc3-dol** [comment]
All the same issues apply to the dataset samples comp.

jfc iii

**Comment by jfc3-dol** [comment]
We should look for a better way to display the code examples that have better color contrast. Don't think people are going to be worried about having different colors to denote different parts of the code.

jfc iii

**Comment by jfc3-dol** [comment]
One point, we should think about for all these comps, is we should use the template and CSS Shirley has built. Doing this will help us make the pages responsive, along with taking a lot of the guess work out of browser testing, etc.

We might have to make a few overrides to the CSS to get the look we are going for, but it's a great start.

jfc iii

**Comment by teo-siewwah** [comment]
My suggestion:

- When coming up the wireframe and functionality for this page, I am thinking that the left nav is sticky sidebar. Something like this http://cfpb.github.io/api/hmda/index.htm
- If this is 12 columns layout, I think the left nav can be about 3 columns or 3 instead of 4 columns as now it seemed. Leave more space for content especially some tables setting and sample scripts.
- the left nav, the section header, I think can be smaller.
- The sub section header can be less indentation.

**Comment by spoonstein** [comment]
@neilneyman fyi - in ref to @steo-dol 's link above, this is a good example of the "sticky"
http://cfpb.github.io/api/hmda/fields.html

**Comment by jfc3-dol** [comment]
?That looks like a nice way to keep the header at the top of the page and the left-side navigation as long as it's not too long on the desktop version of the dataset pages.


jfc iii


John F Croston III



Senior Accessibility Specialist - (CTR)
Office of Public Affairs
U.S. Department of Labor
202-693-5058

________________________________
