### ISSUE TITLE
Getting response blank

### ISSUE THREAD

**Issue by sanketdevrao** [USDepartmentofLabor/Developer#125]
Getting 200 response blank but with blank data

**Comment by hariyerramsetty** [comment]
@sanketdevrao Can you please elaborate the endpoint and the dataset you are trying to query?

**Comment by sanketdevrao** [comment]
Hi,

First of all Thanks for response.

So, some request queries are:


1.       https://data.dol.gov/get/violation/format/json/limit/180

2.       https://data.dol.gov/get/inspection/format/json/limit/180



I am getting response 200 but an empty array.



[cid:image001.png@01D3FCAC.342A53C0]

Thanks,
Sanket

**Comment by hariyerramsetty** [comment]
@sanketdevrao We are currently trying to resolve this issue. Will update you once it is fixed.

**Comment by sanketdevrao** [comment]
Hi Hari,

Could you please give us timeline, when it will be available?

Thanks,
Sanket

**Comment by giridhar** [comment]
The dataset connective has been reestablished please check now. 
sample request
https://data.dol.gov/get/violation/limit/10?X-API-KEY=<yourapikey>
