### ISSUE TITLE
Homepage (mobile)

### ISSUE THREAD

**Issue by waltcerna** [USDepartmentofLabor/Developer#13]
@spoonstein @MikePulsiferDOL This is the first version of the mobile site. With a mockup on the iphone 4. Thoughts?

![dev_iphone4](https://cloud.githubusercontent.com/assets/1934400/5846566/9358b47c-a192-11e4-8e8c-cecfe0d57c74.jpg)
![iphone4_mockup](https://cloud.githubusercontent.com/assets/1934400/5846567/9360126c-a192-11e4-9f3f-a4d17c5ccd5c.jpg)

**Comment by MikePulsiferDOL** [comment]
I really like this.

A LOT.

**Comment by steo-dol** [comment]
Love it! 

The blue background banner for the DOL logo, I think we should stick to the red which is the DOL branding, I think.  Walter, I understand that your team have been using the blue for other use.

**Comment by jfc3-dol** [comment]
I like the comp a lot. The color contrast for the "Beginner" and "Experienced" buttons is inadequate and should be 4.5:1 and they are both around 2.5:1. 

The "Learn More" button over the chart is difficult to read because of color contrast issues too. If you could move the button above the graph that might make it work. Doing so would allow you to increase the font size of the heading next to it to help fill the space, but might cause it to go to a second line.

jfc iii

**Comment by MikePulsiferDOL** [comment]
Are you talking about the contrast between the green and yellow or the colors and the white?

**Comment by jfc3-dol** [comment]
Sorry, for the "Beginner" and "Experienced" buttons I was talking about the background color and the text. For the "Learn More" button, we have contrast issues for both the background color and text, along with the button and the graph.

Will need to check color contrast and for colorblindness issues between buttons.

jfc ii

**Comment by jfc3-dol** [comment]
Here is what our new APIv1 home page will look like for the three main types of color blindness.

As you can see the simulation of Protanope is difficult to see the difference in colors, but having the icons with the words "Beginner" and "Experienced" under them is helpful.

![three main types of color blindness](https://cloud.githubusercontent.com/assets/10423487/5860185/b337da3e-a22d-11e4-9128-96d32cda331f.png)

**Comment by MikePulsiferDOL** [comment]
Given we have text associated with the icons, is the issue with button colors a deal-breaker?  We're not supposed to convey information with color alone anyway.

**Comment by jfc3-dol** [comment]
Deuteranope - a form of red/green color deficit

![deuteranope](https://cloud.githubusercontent.com/assets/10423487/5860753/a36aa970-a231-11e4-9c03-117a0f74dcfa.png)

jfc iii

**Comment by jfc3-dol** [comment]
Protanope - a form of red/green color deficit

![protanope](https://cloud.githubusercontent.com/assets/10423487/5860766/c7a664a0-a231-11e4-867f-8dfb1bce4b60.png)

jfc iii

**Comment by jfc3-dol** [comment]
Tritanope - a blue/yellow color deficit - very rare

![tritanope](https://cloud.githubusercontent.com/assets/10423487/5860790/ec248b9a-a231-11e4-9a4b-3f083ae9c493.png)

jfc iii

**Comment by jfc3-dol** [comment]
I hit the "Comment" button before I was finished and checked my text. So I went back and updated it with the following text.


Here is what our new APIv1 home page will look like for the three main types of color blindness.

As you can see the with the simulation of the "Protanope" color blindness, it's hard to see the difference in colors. Having the icons with the words "Beginner" and "Experienced" under them is helpful.

As you can see some of the background colors for either the buttons or sections look the same or are close in color depending on the type of color blindness, a person might have.

I will add each screenshot into this issues so you can see then larger and more easily.

jfc iii

**Comment by jfc3-dol** [comment]
Correct we shouldn't convey meaning by color alone, but think we need to improve the color contrast as mentioned above so the icons can be noticed by as many people as possible. The more contrast we have within reason, the better people will notice the different icons and buttons.

When I talked with Walter, I mentioned we might want to think about which icons get which colors. What I mean is people tend to notice red more so why not make one of the buttons we want people to click on more have a red background color.

jfc iii

**Comment by waltcerna** [comment]
Here's and updated version of the mockup. Added in the red banner. Adjusted some of the hues and saturation. Changed the CPI section image to something more simple. I am open to ideas on what that image/icon/symbol should be. I made the button a solid color and moved to a better position. 
Also made a few options for the menu. We have the popout, the pushdown, the slideout, the overlay. Just thought I'd give options on how we would want to show the menu.

![dev_iphone4 2](https://cloud.githubusercontent.com/assets/1934400/5920116/08cc5c76-a608-11e4-83d3-632bcc2ebe78.jpg)

![dev_iphone4_popout](https://cloud.githubusercontent.com/assets/1934400/5920115/08c90a30-a608-11e4-8530-9c5bae014583.jpg)

![dev_iphone4_pushdown](https://cloud.githubusercontent.com/assets/1934400/5920118/08cdbcc4-a608-11e4-8ab2-3045d31e2a4d.jpg)

![dev_iphone4_slideout](https://cloud.githubusercontent.com/assets/1934400/5920117/08ccab36-a608-11e4-98f6-8ba5b607d9f4.jpg)

![dev_iphone4_overlay](https://cloud.githubusercontent.com/assets/1934400/5920114/08c8059a-a608-11e4-8db2-4c65e3d2f32a.jpg)

**Comment by steo-dol** [comment]
I just have color issues:
- If red being used on the top banner, I think chose another color for the background of the KEYS button.
- The Burgundy of the menu is too close to the red too.  May be make it darker or black?
- Daniel or Neil, the Foundation CSS has great examples and scripts to do the drop down and slide out menu. 

Check this out if you still use the foundation css. 

Top Bar menus
http://foundation.zurb.com/docs/components/topbar.html

Off-canvas menus
http://foundation.zurb.com/docs/components/offcanvas.html#idOfRightMenu

**Comment by jfc3-dol** [comment]
Walter,

Thanks, for increasing the color contrast of the buttons in this comp. The yellow/gold one still does not have enough contrast. It's has a color contrast ratio of 2.29:1 when it needs to be 4.5:1.

Liking the different menu options as long as we can come up with a keyboard and screen reader accessible version that is responsive as well I'm okay with it. Will give this all a bit more thought to see if we need anything else.

jfc iii

**Comment by jfc3-dol** [comment]
Looking at the comp further I noticed the red in the DOL header ( #9A0000 ) is different from the red  ( #990000 ) we currently use.

jfc iii

**Comment by waltcerna** [comment]
@jfc3-dol 
The red is #990000. Again when you use a color picker you will get different reds based on the pixel that the picker lands on. Per the PSD file the red is #990000.
Thanks!

**Comment by waltcerna** [comment]
Here is a mockup of the different sizes of the mobile homepage and what they would like on the different phones. From the iPhone 4s – 6+.

![mobile](https://cloud.githubusercontent.com/assets/1934400/6026684/bd799042-abaa-11e4-945b-14e4ba0b837c.jpg)

**Comment by spoonstein** [comment]
@waltcerna 

- [ ] Different red and gold background colors are needed
- [ ] Footer will be minimal one-liner with left-side (west-side) column

**Comment by waltcerna** [comment]
@spoonstein Here are the edits. Modified the colors a bit and added the footer.
![dev_iphone4 3](https://cloud.githubusercontent.com/assets/1934400/6176152/68189284-b2ca-11e4-8828-c408790d915f.jpg)

Above is the smaller screen, below is the larger screen

![large_smartphone2](https://cloud.githubusercontent.com/assets/1934400/6176150/681331c2-b2ca-11e4-8a61-288cb9512e4b.jpg)

And this is what it would look like on the phones labeled and sized accordingly...

![mobile2](https://cloud.githubusercontent.com/assets/1934400/6176149/6812ab30-b2ca-11e4-977f-74fe3c1d0aa9.jpg)

**Comment by jfc3-dol** [comment]
Looking nice sir. The color contrast for the gold it still low, but people screen brightness and sun glare, etc. will affect these colors too.

**Comment by waltcerna** [comment]
@jfc3-dol I know... the gold/orange color is driving me insane... Thats the only one I can't seem to get passed the 508 checker.. to make it 508 it keeps giving me a brownish color which I refuse to use.

**Comment by spoonstein** [comment]
Maybe consider a different color all-together?

**Comment by waltcerna** [comment]
@spoonstein This is the flow chart I have so far.
![currentflow](https://cloud.githubusercontent.com/assets/1934400/6275045/194dee4e-b84a-11e4-959a-8dfa48540fba.jpg)

**Comment by spoonstein** [comment]
@waltcerna edits from our meeting last week.
- [ ] Hide logo
- [ ] Portal above DOL name
- [ ] More kerning in header title
- [ ] Regular case sub-nav items
- [ ] Let's discuss the button layout

**Comment by waltcerna** [comment]
@spoonstein @MikePulsiferDOL  @jfc3-dol @steo-dol 
Here is the new metro-like home page. Updated the header. 
* Hid the Logo
* Flipped the Developer Portal text to be on top of the US DOL text.
* Added kerning and tracking to the text to open it up more.
* Made sure all colors pass 508.
```
Green = #265447
Blue = #2b5681
Maroon = #732222
Purple = #7b3b76
Dark Blue = #2c3e50
Dark Grey = #434343
Red = #990000 
```
![dev_iphone4 4](https://cloud.githubusercontent.com/assets/1934400/6337969/6d1039ec-bb79-11e4-9fa1-96dad94898b4.jpg)

**Comment by waltcerna** [comment]
@spoonstein 
## New designed homepage
Color pending... of course.
![mobile_dev_site_0006_homepage](https://cloud.githubusercontent.com/assets/1934400/6718166/137cc276-cd88-11e4-9b25-e5363b2239c8.jpg)

**Comment by spoonstein** [comment]
Thanks @waltcerna 
Please ref #27 for VETS content, not CPI content.

The Apple/GPlay buttons need to reflect the Labor Stats App, not the stores.

**Comment by waltcerna** [comment]
@spoonstein 
Heres the updated home and the flow.

![mobile_dev_site_0009_homepage](https://cloud.githubusercontent.com/assets/1934400/6741094/599bf8b6-ce5b-11e4-8534-997a5531a5fe.jpg)

![currentflow](https://cloud.githubusercontent.com/assets/1934400/6741098/60decc8e-ce5b-11e4-8783-dd644621da80.jpg)

**Comment by jfc3-dol** [comment]
Nice, examples in the phone.

**Comment by joey-spooner** [comment]
@waltcerna edits/changes:
- [x] Update VETS layout as discussed in person
- [x] Update Labor Stats to use title, text, and single button (platform dependent) to download the app

**Comment by waltcerna** [comment]
@spoonstein 
Updated App section.
![mobile_dev_site_0010_homepage](https://cloud.githubusercontent.com/assets/1934400/6971145/675a4e38-d948-11e4-8b6d-a3cffcf0c75b.jpg)

**Comment by waltcerna** [comment]
@spoonstein 

## Current Flow

![currentflow_v2](https://cloud.githubusercontent.com/assets/1934400/6966477/57b8f324-d927-11e4-9028-9b3f8584a198.jpg)

**Comment by joey-spooner** [comment]
Excellent. Looking forward to reviewing it tomorrow.

**Comment by joey-spooner** [comment]
@MikePulsiferDOL please review and confirm that you're ready for @neilneyman to break this down into code.

**Comment by MikePulsiferDOL** [comment]
👍🏼

**Comment by neilneyman** [comment]
@MikePulsiferDOL For the platform-dependent Download Free App (labor stats) button,  my thinking is we should use the github repo as a fall-back option if the device is neither apple nor android?      This would be consistent with the three options on the desktop version

**Comment by MikePulsiferDOL** [comment]
No.  If someone has a Windows phone, the source code won't help them any.  If they're not using iOS or Android, and it's not mentioned elsewhere in that "ad," then we should have it say "Available for iPhone and Android" in place of the buttons.

**Comment by neilneyman** [comment]
@MikePulsiferDOL The most-recent design has a single button -- but the link is device-dependent.    Do we want to show something different for other devices?

**Comment by MikePulsiferDOL** [comment]
Yeah, "Available for iPhone and Android"  Keep the buttons that we've been using where appropriate.

**Comment by joey-spooner** [comment]
@neilneyman I spoke with @MikePulsiferDOL and confirmed the following configuration:
- If you're not Apple or Andriod, then remove the link and show text "Available for iPhone and Android"
- If you're on Apple or Android, then link to the appropriate store location and continue to hide "Available for iPhone or Android"

**Comment by adams-lisa** [comment]
verification & UAT complete. Pushed to v1.0.0
