### ISSUE TITLE
Unable to access API Data.dol.gov V2 using Python Requests Package

### ISSUE THREAD

**Issue by arjitsakhuja** [USDepartmentofLabor/Developer#138]
First of all, the information on the website is ambiguous because we do not know what X stands for in the key/value pair: "X-API-KEY: d9c6c290-da4c-424e-a378-fb4bd027b58z". In my case, I am using X as my application name which is 'DOL'

Here is my Python code. I am following the protocols given on the official website but still getting 403 status code
Code:
header = {"DOL-API-KEY":'My Token'}  
response = requests.get("https://data.dol.gov/get/violation_event",headers=header)
response.status_code
# Output: 403

Also, I double checked to see if my token is valid or not by using the following code:

header = {'Accept':'application/json'}
response = requests.get("http://api.dol.gov/V1/DOLAgency/Agencies/?KEY=My Token",headers=header)
response.status_code
# Output: 200

Please help me out and tell me where things are going wrong. Thank You!

**Comment by hariyerramsetty** [comment]
@arjitsakhuja: X in X-API-KEY doesn't have any specific meaning. So when you are calling API. The key should be passed as X-API-KEY

Ex: ```https://data.dol.gov/get/<datasettable-name>/limit/10?X-API-KEY=<your-api-key>```

**Comment by arjitsakhuja** [comment]
Thank you so much for helping me out.

Kind regards,
Arjit Sakhuja
