### ISSUE TITLE
Unable to access OSHA COMPLIANCE v1 through https request

### ISSUE THREAD

**Issue by arjitsakhuja** [USDepartmentofLabor/Developer#139]
As per the protocols, I am trying to fetch data related to **OSHA inspections** present in tables: **full, foodservice, hospitality, retail, occupationcode, substancecode** mentioned in this link "https://developer.dol.gov/health-and-safety/dol-osha-compliance/#full". I am using Python Requests package to fetch inspection data related to retail from this URL : "http://api.dol.gov/V1/Compliance/retail/?KEY=MyKey" which is not working and giving me #404 error. Whereas the same protocol for DOL Agency data is working perfectly fine when I use this URL "http://api.dol.gov/V1/DOLAgency/Agencies/?KEY=MyKey".

 Please help me to figure out this issue.

**Comment by hariyerramsetty** [comment]
@arjitsakhuja: As discussed in #138, please change KEY to X-API-KEY. Thanks
