### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by spoonstein** [USDepartmentofLabor/Developer#14]
Include the location of the homepage on github.io

**Comment by spoonstein** [comment]
Ref #7 for design.

**Comment by spoonstein** [comment]
Also, within #7 please comment (here) with questions from #7 and answers for the UX/508 items.

**Comment by spoonstein** [comment]
URL - http://usdepartmentoflabor.github.io/Developer/

**Comment by spoonstein** [comment]
@waltcerna update header with portal title.

**Comment by spoonstein** [comment]
@neilneyman 
* Use page title of "Developer Portal - United States Department of Labor". 
* Fix the menu. 
* Change order of Beginner and Experience buttons make font bigger or bold for all buttons on page.
* Left justify the "Labor Stats" text. Add more space between the two buttons in this section.
* Left justify the text in the "Consumer Price Index" section.
* Under "Grab Our Code" section need to left justify text and maybe add extra span to keep it from filling the space.
* Support menu item will be a drop-down with sub-menu items, not a page. Flush it right beyond the About menu item.
* Include API Keys button.

**Comment by waltcerna** [comment]
@spoonstein Updated Homepage with new header and alignment of text sections.

This is the new banner... had to shrink the search box a bit to be able to fit the social icons.
![banner](https://cloud.githubusercontent.com/assets/1934400/6177528/9b10395c-b2d5-11e4-8bba-fbe73b5916a8.jpg)

Homepage with new banner.
![dol_dev_homepage](https://cloud.githubusercontent.com/assets/1934400/6177527/9b0e821a-b2d5-11e4-9034-f53bf364df89.jpg)

**Comment by spoonstein** [comment]
Tasks for @neilneyman

Header
[ ] Update navigation font size to reflect design

Grab Our Code
[ ] Remove description fields from Grab Our Code 
[ ] Use title "SDK", etc. as button labels
[ ] Make icon and button as active links

**Comment by neilneyman** [comment]
latest changes are up on developerportal

**Comment by spoonstein** [comment]
Thanks! Please add the following language underneath the header for Grab Our Code.

Use one of our many SDK's to quickly connect and query the DOL API as well as many other federal agencies. We offer SDK's in many popular languages including C#, PHP, Ruby, Objective-C, and Swift.

You can also download or browse our mobile, web, and desktop application source code to understand how we use the DOL API for our needs. 

@MikePulsiferDOL please comment if you feel changes are needed.

**Comment by neilneyman** [comment]
@spoonstein added

**Comment by neilneyman** [comment]
Reassigning this to QA now, changes are on developerportal dev site

**Comment by MikePulsiferDOL** [comment]
Search needs to use USASearch to search developer.
