### ISSUE TITLE
Invalid API Key for V2 APIs

### ISSUE THREAD

**Issue by vinayan** [USDepartmentofLabor/Developer#141]
I am getting "Invalid API Key" for all the V2 requests.

My Curl Request(from referring  https://developer.dol.gov/accessing-the-apis-using-http-requests/) :

`curl -H "X-API-KEY:mytoken" https://data.dol.gov/get/accident/format/xml/limit/10`

The same key works for V1 API without issues when passed as a query parameter named "KEY".

Any ideas?

**Comment by savannahmhunter** [comment]
My team and I are having the same issue. Our code was in the same format except we were trying to call the inspection data. We also tried examples using version 1 of other data and that worked but for the inspection data only version 2 is available.

**Comment by giridhar** [comment]
Hi, @savannahmhunter and @vinayan sorry to hear that you are unable to get to the data. can you please try 
https://data.dol.gov/get/accident/limit/10/?X-API-KEY=<your api key>   and let me know if you see any error.

**Comment by vinayan** [comment]
hi, @giridhar  I still get "Invalid" API key 


![apikey](https://user-images.githubusercontent.com/1298627/69513470-d9506d00-0f6d-11ea-8fbb-01421833f336.png)

**Comment by vinayan** [comment]
@giridhar any update?

**Comment by giridhar** [comment]
That's Wierd can you please share your account details via email to webmaster at dol dot gov. I can take a look at it.

**Comment by savannahmhunter** [comment]
I am also get the same error message.
![2019-12-03 (2)](https://user-images.githubusercontent.com/39849088/70110449-d99ed700-1603-11ea-8837-7e4b177320fb.png)

**Comment by vinayan** [comment]
@giridhar I sent the account details to the specified email. Please take a look.

**Comment by giridhar** [comment]
Can you please check now.

**Comment by giridhar** [comment]
Closing this now.
