### ISSUE TITLE
Inspection table returning 0 results

### ISSUE THREAD

**Issue by patbluenote** [USDepartmentofLabor/Developer#142]
This was working before but now if I perform a GET on https://data.dol.gov/get/inspection/limit/1/offset/0 I get back an empty array, regardless of offset or limit up to 200.

**Comment by giridhar** [comment]
@patbluenote did you try with your api key ? 

https://data.dol.gov/get/inspection/limit/1/offset/0?X-API-KEY=<yourkey>

**Comment by patbluenote** [comment]
Yes.  It started working again on Sunday.  Late Friday when I first reported it was returning [] and Saturday when I checked it was the same but Sunday it started working.  Also, without the API key, it returns:
{
"status": "",
"error": "Invalid API Key"
}
