### ISSUE TITLE
Define where to look up Hazardous substance code for "hazsu(1-5)" and "nr_instances"

### ISSUE THREAD

**Issue by shapironick** [USDepartmentofLabor/Developer#143]
hello!
@premolina492 and I are looking through the OSHA violation dataset and we're trying to figure out where to look up the codes in hazsu1-hazsu5 and have poured over the documentation but haven't found anything. we know they are 4 digits and alphanumeric but where do we find where these codes are defined? Can you point us to where to find this data? 

also can you point us to where the number of instances is defined? like, how do you distinguish what counts as one vs two instances? 

Thank you!

**Comment by hariyerramsetty** [comment]
@shapironick: This website contains data related to enforcement data (OSHA Violation etc)

https://enforcedata.dol.gov/views/data_summary.php

Incase you need additional information that is not available on the enforcement data website, please send an email to webmaster@dol.gov. The request will be directed to appropriate dataowner

**Comment by shapironick** [comment]
Thank you! We just sent an email as we cannot find the information we are looking for there or on other parts of the website that we've scoured. Closing as this is moving to email. Thanks again!
