### ISSUE TITLE
date_column filtering not working

### ISSUE THREAD

**Issue by tonydifranco** [USDepartmentofLabor/Developer#144]
I've tried filtering by date using the [api v2](https://developer.dol.gov/accessing-the-apis-using-http-requests/#apiv2) methodology on multiple tables and columns and I always get the same error response.  Is this functioning properly?

example url:
https://data.dol.gov/get/inspection/limit/20/date_column/open_date/start_date/2019-06-15

```
{
    "status": "0",
    "error": "Not Acceptable. Check suggested format."
}(base)
```

**Comment by giridhar** [comment]
We apologize but this feature is not functioning properly at this time.  Although it is not ideal, please download the complete dataset and apply the date filter as needed.  We expect an improvement with filtering in the near future.  Thank you.

**Comment by tonydifranco** [comment]
@giridhar is there a way to download the complete table without having to paginate?

I think just found it: https://enforcedata.dol.gov/views/data_summary.php

**Comment by giridhar** [comment]
I am afraid that's the only way we can get all the data (paginate).
