### ISSUE TITLE
Compliance/WHD is not found

### ISSUE THREAD

**Issue by ghost** [USDepartmentofLabor/Developer#148]
None of the dataset tables listed [here](https://developer.dol.gov/wage-and-hour-division/whd-compliance/) are available. They all return a 503 response and body contents of a "404 error" message:

![image](https://user-images.githubusercontent.com/79165935/113457240-880b8580-93cc-11eb-90f0-ca96d708f22b.png)

When using the [API Sampler](https://devtools.dol.gov/APISampler/Home/Index1?datasetName=DOL%20Compliance-WHD) for that same dataset, it also doesn't return anything. It just resets the form.

Is this dataset simply no longer available and the documentation out of date? Or is the database connectivity broken?

**Comment by giridhar** [comment]
Please accept our apologies for your APIv1 and API Sampler experience.  We are diligently working on an improved API dataset catalog along with API capabilities.  As these capabilities are ready for release, announcements will be posted via our developer website. Thank you.
