### ISSUE TITLE
CPS & OES return 503 when trying to access tables

### ISSUE THREAD

**Issue by calebswank11** [USDepartmentofLabor/Developer#149]
I can access the table response accurately but cannot query any data on the tables. It seems like any api's under Expanding Growth and Opportunities & Learning are having this issue, at least any with all caps snake case tables. I can access Public Workforce System and IPIA but not CPS, CES, CPI

Just to note, response text says 404, but actual response is 503

Please advise.

![image](https://user-images.githubusercontent.com/9935867/122281623-12359700-ceb0-11eb-8e91-c5a6acd300fa.png)

**Comment by kgrabhorn-dol** [comment]
@calebswank11, thank you for reaching out to us about your API experience.  We are aware of these issues and are diligently working on an improved API dataset catalog along with API capabilities. As these capabilities are ready for release, announcements will be posted via our developer website.  Until these capabilities are available, please visit the respective BLS websites for CPS, CES, and CPI data.

[https://www.bls.gov/cps](https://www.bls.gov/cps)
[https://www.bls.gov/ces](https://www.bls.gov/ces)
[https://www.bls.gov/cpi](https://www.bls.gov/cpi)

Thank you.
