### ISSUE TITLE
Beginner page

### ISSUE THREAD

**Issue by spoonstein** [USDepartmentofLabor/Developer#15]

**Comment by spoonstein** [comment]
Ref #9 for design. @waltcerna can give you slices.

**Comment by spoonstein** [comment]
Please ref #9 for UX/508 concerns. Copy/paste questions into this issue so we can keep the thread here.

**Comment by waltcerna** [comment]
@spoonstein 
Updated Beginner page with icon from mobile version to keep consistency. Added the new banner as well.
![novice6](https://cloud.githubusercontent.com/assets/1934400/6177607/089198ae-b2d6-11e4-9223-961072cee40e.jpg)

**Comment by waltcerna** [comment]
@spoonstein 
* Updated intro section to reflect color background and text color 
![novice7](https://cloud.githubusercontent.com/assets/1934400/6338383/818e7336-bb7c-11e4-868a-1d9f4d89483c.jpg)
of  mobile homepage #13

**Comment by spoonstein** [comment]
@waltcerna please provide @neilneyman the slices.

**Comment by neilneyman** [comment]
@spoonstein This has been updated
