### ISSUE TITLE
Search on date_column not working

### ISSUE THREAD

**Issue by r2rahul** [USDepartmentofLabor/Developer#150]
Posting this Stack Exchange question for the possible solution https://opendata.stackexchange.com/questions/19821/url-to-search-dol-api-data-dol-gov-v2-to-access-osha-enforcement-data

I am also trying to get data based on start and end date, but I am getting the following error message:
Query: "https://data.dol.gov/get/inspection/?format =json&limit=200&date_column=OPEN_DATE&start_date=2020-12-12" and Error message is {
    "status": "0",
    "error": "Not Acceptable. Check suggested format."
}

The query is constructed based on help provided at: https://developer.dol.gov/accessing-the-apis-using-http-requests/#apiv2

**Comment by giridhar** [comment]
@r2rahul , we apologize but this feature is not functioning as expected at this time. We are diligently working on an improved API dataset catalog along with API capabilities. As these capabilities are ready for release, announcements will be posted via our developer website. Until these capabilities are available, we can suggest a couple of alternatives, both of which require downloading the complete dataset and filtering the date locally.  You may use the API to download the OSHA Inspection data or you may obtain the complete dataset from the Enforcement Data Portal (https://enforcedata.dol.gov/views/data_catalogs.php). Thank you.
