### ISSUE TITLE
Invalid API Key

### ISSUE THREAD

**Issue by spencer-kimball** [USDepartmentofLabor/Developer#151]
Hello,

I'm trying to access OSHA Inspection data through DOL's API, but it's telling me I have an invalid key. I created a new key, and I'm still getting the invalid response.

`Response [https://data.dol.gov/get/inspection]
  Date: 2021-09-15 16:28
  Status: 403
  Content-Type: application/json; charset=utf-8
  Size: 52 B
{
    "status": "",
    "error": "Invalid API Key"`

Any idea what could be causing this? I know there was a previous thread on this topic, but I didn't see a clear resolution of the issue, other folks also seemed to be experiencing it. 

I am using R to access the API.

`osha_response <- GET('https://data.dol.gov/get/inspection', add_headers('X-API-KEY: TK'))`

Thank you for your help.

**Comment by kgrabhorn-dol** [comment]
@spencer-kimball, for API version 2 datasets, please use "X-API-KEY" instead of "KEY".  For the OSHA Inspection dataset, the query would be as follows:

https://data.dol.gov/get/inspection/limit/100?X-API-KEY=

Let us know how it goes.  Thank you

**Comment by spencer-kimball** [comment]
Is entering the limit for rows required for a successful response?

**Comment by kgrabhorn-dol** [comment]
@spencer-kimball, good morning, yes.  A record limit is required and the maximum limit for API version 2 datasets is 200.  Thank you

**Comment by spencer-kimball** [comment]
Good afternoon. Understood. 

How then do I pull all the records available for this dataset? Or even determine how large the dataset is to begin with? I imagine the enforcement dataset has much more than 200 records in it. 

Best,

Spencer

**Comment by kgrabhorn-dol** [comment]
@spencer-kimball, we are diligently working on an improved API dataset catalog along with API capabilities. As these capabilities are ready for release, announcements will be posted via our developer website. Until these capabilities are available, we can suggest a couple of methods to obtain the full dataset.  You may use the API to download the OSHA Inspection data 200 records at a time or you may download the complete dataset from the Enforcement Data Portal (https://enforcedata.dol.gov/views/data_catalogs.php). 

To use the API, your get requests will take on the following structure:
https://data.dol.gov/get/inspection/limit/200/offset/0?X-API-KEY=
https://data.dol.gov/get/inspection/limit/200/offset/200?X-API-KEY=
https://data.dol.gov/get/inspection/limit/200/offset/400?X-API-KEY=
...
https://data.dol.gov/get/inspection/limit/200/offset/4840800?X-API-KEY=

Thank you

**Comment by spencer-kimball** [comment]
Thank you, look forward to the improved API dataset.

In the meantime, is there anybody at DOL I can speak with about the OSHA inspections dataset? I need a bit of help deciphering what some of the column titles mean. 

Best,

Spencer

**Comment by kgrabhorn-dol** [comment]
@spencer-kimball, in addition to the developer site (https://developer.dol.gov/health-and-safety/dol-osha-enforcement/#osha_inspection), you may see if this table helps you decipher the column headings.  Thanks

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/GRABHO~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/GRABHO~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



variable | description
-- | --
REPORTING_ID | Area Office Reporting   ID
STATE_FLAG | State Plan Indicator
SITE_ADDRESS | Inspection Site   Street Address
SITE_CITY | Inspection Site City
SITE_STATE | Inspection Site State
SITE_ZIP | Inspection Site Zip
SAFETY_HLTH | Safety or Health   Inspection
SIC_CODE | Standard Industry   Classification (SIC) Code
INSP_TYPE | Inspection Type
UNION_STATUS | Indicates whether or   not employees on site are represented by a union.
SAFETY_MANUF | Safety Inspection in   Manufacturing Indicator
SAFETY_CONST | Safety Inspection in   Construction Indicator
SAFETY_MARIT | Safety Inspection in   Maritime Indicator
HEALTH_MANUF | Health Inspection in   Manufacturing Indicator
MAIL_STREET | Establishment Mailing   Street Address
MAIL_STATE | Establishment Mailing   State
MAIL_ZIP | Establishment Mailing   Zip Code
CLOSE_CONF_DATE | Closing Conference   Date of Inspection
LD_DT | File Loaded Date
ID | ID Number
ACTIVITY_NR | Activity (Inspection)   Number
ESTAB_NAME | Establishment Name
OWNER_TYPE | Ownership Type
OWNER_CODE | Ownership Code
ADV_NOTICE | Advance Notice   Indicator
NAICS_CODE | North American   Industry Classification System (NAICS) Code
INSP_SCOPE | Inspection Scope
WHY_NO_INSP | Why Was There No   Inspection?
HEALTH_CONST | Health Inspection in   Construction Indicator
HEALTH_MARIT | Health Inspection in   Maritime Indicator
MIGRANT | Migrant Labor   Inspection Indicator
MAIL_CITY | Establishment Mailing   City
HOST_EST_KEY | Host Establishment   Key
NR_IN_ESTAB | Number of Employees   in Establishment
OPEN_DATE | Inspection Opened   Date
CASE_MOD_DATE | Date Case was Last   Modified
CLOSE_CASE_DATE | Case Closed Date



</body>

</html>

**Comment by spencer-kimball** [comment]
Unfortunately, it leaves some unanswered questions. The column headings are one issue, and then the representation of values under each column are another.  

For example, values under inspection scope are represented as letters. However, the explanation of what each value means is brief in DOL website material. For example C = Records. Not sure that records means.

**Comment by kgrabhorn-dol** [comment]
@spencer-kimball, I am reaching in to our data community in hopes we can provide you an answer.  It may take a few days to obtain a response.  Thank you

**Comment by kgrabhorn-dol** [comment]
@spencer-kimball, the following is provided in response to your question.  Thank you

-----------------------------
OSHA’s policies on inspections include the following:

A. Comprehensive. 
A comprehensive inspection is a substantially complete and thorough inspection of all potentially hazardous areas of the establishment. An inspection can be deemed comprehensive even though, as a result of professional judgment, not all potentially hazardous conditions or practices within those areas are inspected. 
B. Partial. 
A partial inspection is one whose scope is limited to certain potentially hazardous areas, operations, conditions, or practices at the establishment.

In addition, a scope of Records Only indicates that the OSHA inspection was limited to looking at the Part 1904 records that many establishments are required to keep.

A scope of No Inspection indicates that an OSHA inspection was unable to be carried out at the establishment (e.g. it was found to be out of business).

**Comment by spencer-kimball** [comment]
EDIT: Sorry let me be more precise.

I have found the tables that include OSHA data on violations and penalties. There is an OSHA violations table, an OSHA violation event table, and a table on violations of the general duty clause.

I am trying to use these tables to find two pieces of data: How many violations did OSHA issue in a given year, and how many resulted in financial penalties.

My question: Which of the above mentioned datasets is best to use to determine these figures? I'm getting different numbers when I add up the number of violations in the violations table and the violations event tables.

**Comment by spencer-kimball** [comment]
For example, in OSHA's violation event table, the sum of all penalties (hist_penalty) for the year 2021 equals $385,616,889.

However, in OSHA's violations table, the sum of all penalties (current_penalty) for the year 2021 equals $176,373,177.

Yet, in the lab on the enforcement page website (https://enforcedata.dol.gov/views/oshaLab.php), penalties for the year 2021 equal  $101,310,787.19 

I am having a very difficult time determining which of these three figures is the correct one. I plan on using this data in reporting for CNBC, so any information you can provide on the discrepancy would be a big help. Thank you! 

Best,

Spencer

**Comment by kgrabhorn-dol** [comment]
@spencer-kimball, I am closing this issue as the topic of "Invalid API Key" has been resolved.  You created topic #152 that replicates the last post made here. Thank you
