### ISSUE TITLE
Data issue, OSHA violation event vs OSHA violations tables

### ISSUE THREAD

**Issue by spencer-kimball** [USDepartmentofLabor/Developer#152]
Hello,

I am searching for the annual dollar value of penalties imposed by OSHA for violations. I am searching through the relevant available tables, the OSHA violation event table and OSHA violations table, and I am getting different numbers.

For example, in OSHA's violation event table, the sum of all penalties (hist_penalty) for the year 2021 equals $385,616,889.

However, in OSHA's violations table, the sum of all penalties (current_penalty) for the year 2021 equals $176,373,177.

Yet, in the lab on the enforcement page website (https://enforcedata.dol.gov/views/oshaLab.php), penalties for the year 2021 equal $101,310,787.19

I am having a very difficult time determining which of these three figures is the correct one. I plan on using this data in reporting for CNBC, so any information you can provide on the discrepancy would be a big help. Thank you!

Best,

Spencer

**Comment by kgrabhorn-dol** [comment]
@spencer-kimball, I am reaching in to our data community in hopes we can provide you an answer. It may take a few days to obtain a response. Thank you

**Comment by kgrabhorn-dol** [comment]
@spencer-kimball, DOL produces official OSHA numbers with data run in mid-November.  OSHA data in DOL's Enforcement Data Portal and API are updated daily.  Therefore it will be difficult to obtain the official OSHA numbers without precise timing or having the algorithm used to produce the report.  It is recommended that you visit OSHA's Newsroom https://www.osha.gov/news to obtain accurate numbers via the FOIA process, contacting OSHA Office of Communications, or making a request to the DOL Office of Public Affairs.  Thank you.
