### ISSUE TITLE
DOL API is throwing an error "The URI you submitted has disallowed characters." when we are trying to call the API by filtering on the columns

### ISSUE THREAD

**Issue by pricingmodel** [USDepartmentofLabor/Developer#154]
DOL API is throwing an error "The URI you submitted has disallowed characters." when we are trying to call the API by filtering on the columns

Request: https://data.dol.gov/get/inspection/limit/200/filter_column/SITE_ADDRESS=3300 EDISON WAY:SITE_CITY=FREMONT:SITE_STATE=CA:SITE_ZIP=94538

Please note this was working couple of weeks ago and we noticed this issue just today (06/02)

**Comment by kgrabhorn-dol** [comment]
@pricingmodel, we are analyzing the issue you reported and will provide a response by the end of the day.  Thank you.

**Comment by kgrabhorn-dol** [comment]
@pricingmodel, thank you for reporting the issue.  It has been resolved and your query provides results once again.  Thank you.

**Comment by pricingmodel** [comment]
Thank You @kgrabhorn-dol. We are now seeing proper responses from the API

**Comment by pricingmodel** [comment]
@kgrabhorn-dol : We see that the issue is resolved but the filtering is not happening. For example the below request is returning the results that do not match the search criteria

https://data.dol.gov/get/inspection/limit/200/filter_column/ESTAB_NAME=LEE'S IMPERIAL WELDING INC:SITE_ADDRESS=3300 EDISON WAY:SITE_CITY=FREMONTSITE_STATE=CA:SITE_ZIP=94538

Could you please take a look at the issue.

**Comment by pricingmodel** [comment]
@kgrabhorn-dol : Could you please take a look at the above issue

**Comment by kgrabhorn-dol** [comment]
@pricingmodel, our team has analyzed this issue and are preparing to release an update to our code.  I will post an update here once it is ready for you to use.  Thank you, @kgrabhorn-dol

**Comment by kgrabhorn-dol** [comment]
The code for APIv2 was updated.  The reported issue is fixed with this update.  I'll keep this issue open for a couple of days for you to have an opportunity to verify.  Thank you, @kgrabhorn-dol
