### ISSUE TITLE
Unable to connect to data.dol.gov

### ISSUE THREAD

**Issue by pricingmodel** [USDepartmentofLabor/Developer#156]
We are unable to connect to data.dol.gov. We are getting an error. 

![image](https://user-images.githubusercontent.com/106754087/183131168-4f8a6ac4-5a67-4f4d-a5e5-8dc859f11683.png)

**Comment by kgrabhorn-dol** [comment]
@pricingmodel, we have verified the issue you reported and escalated to our operations team.

**Comment by kgrabhorn-dol** [comment]
@pricingmodel, APIv2 is operational once again.  Thank you again for reporting the issue.
