### ISSUE TITLE
The Mining/FullMineInfo/MSHA_mines gives the MINE_ID in scientific notation and Date in unix timestamp * 1000

### ISSUE THREAD

**Issue by deanm0000** [USDepartmentofLabor/Developer#159]
As the title says, the MINE_ID comes through in scientific notation for IDs with more than 6 digits.  This is some what ironic in that it uses 5 characters (e+006) to replace just the last digit of a 7 digit number.  Having all 7 digits is important in matching this dataset with what the EIA has.

As far as the date field, one example is Date(551577600000) which seems to be a unix timestamp with 3 extra 0s.

**Comment by kgrabhorn-dol** [comment]
Thank you for your post.  The mine_id field in our legacy API is formatted incorrectly.  We are diligently working on an improved API dataset catalog along with API capabilities. As these capabilities are ready for release, announcements will be posted via our developer website. Until these capabilities are available, we suggest an alternative way for you to access the same MSHA data.  Please visit the Enforcement Data Portal and download the "msha_mine" file.  Thank you.

Enforcement Data Portal
https://enforcedata.dol.gov/views/data_catalogs.php
