### ISSUE TITLE
SDK page

### ISSUE THREAD

**Issue by spoonstein** [USDepartmentofLabor/Developer#16]
Remember to include root page for SDK's and comment as you go each day.

**Comment by spoonstein** [comment]
Ref #11 for design. @waltcerna can slice up images for you when you're ready.

**Comment by MikePulsiferDOL** [comment]
Exploring the use of GitHub's gists: http://usdepartmentoflabor.github.io/Swift-Sample-App/

**Comment by MikePulsiferDOL** [comment]
Let's move issues for SDK documentation design changes to those repos.
