### ISSUE TITLE
Experienced Page

### ISSUE THREAD

**Issue by waltcerna** [USDepartmentofLabor/Developer#20]
Ref #8 for previous comments and original thread.
Starting new issue for updates

**Comment by waltcerna** [comment]
Updated experienced page with new icon and banner.

![developers_mockup7](https://cloud.githubusercontent.com/assets/1934400/6177679/822ed208-b2d6-11e4-8852-47946e316b16.jpg)

**Comment by spoonstein** [comment]
@waltcerna please update the background color to match that of the mobile version. This goes for the coloring of the icons, text, button, etc. too.

**Comment by waltcerna** [comment]
@spoonstein 
* Updated background color and text/icon color to reflect mobile site.
![developers_mockup9](https://cloud.githubusercontent.com/assets/1934400/6338408/a8763042-bb7c-11e4-854f-839cd3d6f038.jpg)

**Comment by spoonstein** [comment]
@waltcerna please give @neilneyman the updated slice for the dev guide section.

**Comment by neilneyman** [comment]
@spoonstein updated

**Comment by spoonstein** [comment]
@MikePulsiferDOL can you provide links for the mobile and web/desktop apps?
