### ISSUE TITLE
SDK Page (mobile)

### ISSUE THREAD

**Issue by spoonstein** [USDepartmentofLabor/Developer#22]

**Comment by waltcerna** [comment]
## SDKs

![sdk_main](https://cloud.githubusercontent.com/assets/1934400/6472047/8306a30e-c1bd-11e4-8451-125c070e33cc.jpg)

![sdk_2ndlevel](https://cloud.githubusercontent.com/assets/1934400/6472046/83069878-c1bd-11e4-9a1b-ada61b0664dc.jpg)

**Comment by waltcerna** [comment]
@spoonstein 
Updated dropdown.
![mobile_dev_site_0000_sdk dropdown](https://cloud.githubusercontent.com/assets/1934400/6741223/34aad53a-ce5c-11e4-923b-f933132f3371.jpg)

**Comment by jfc3-dol** [comment]
Liking the gray gutter to create buttons, but think we need to make it darker for better color contrast.

**Comment by joey-spooner** [comment]
@waltcerna SDKs not SDKS. ;)

**Comment by adams-lisa** [comment]
verification & UAT complete. Pushed to v1.0.0
