### ISSUE TITLE
Dataset Page (mobile)

### ISSUE THREAD

**Issue by spoonstein** [USDepartmentofLabor/Developer#23]

**Comment by waltcerna** [comment]
## Datasets

![dataset_mainmenu](https://cloud.githubusercontent.com/assets/1934400/6470026/d4735d40-c1ae-11e4-8eb3-faa88b4a392b.jpg)

![dataset_2ndlevel](https://cloud.githubusercontent.com/assets/1934400/6470024/d46cd768-c1ae-11e4-86d7-4a7d41cf7ba7.jpg)

![dataset_3rdlevel](https://cloud.githubusercontent.com/assets/1934400/6470025/d47072ba-c1ae-11e4-871a-cf630d6e7d94.jpg)

![dataset_3rdlevel_detail](https://cloud.githubusercontent.com/assets/1934400/6470023/d46be68c-c1ae-11e4-970f-db67d31593b7.jpg)

**Comment by waltcerna** [comment]
### New Dataset 2nd Level
![dataset_2ndlevel_v2](https://cloud.githubusercontent.com/assets/1934400/6622000/3a3d290a-c8b0-11e4-8a27-62a4fcf3a759.jpg)

**Comment by waltcerna** [comment]
@spoonstein 
Updated 2nd view and 3rd view.
![mobile_dev_site_0002_datasets dropdown](https://cloud.githubusercontent.com/assets/1934400/6741254/60256fc2-ce5c-11e4-803f-93ab0fc25b6e.jpg)

![mobile_dev_site_0001_dataset details](https://cloud.githubusercontent.com/assets/1934400/6741253/602198a2-ce5c-11e4-8848-2eaa96876e94.jpg)

**Comment by jfc3-dol** [comment]
Liking how we have the gutter between buttons in red(ish). Not sure if it would be better to have the horizontal line go to the edge of the screen width to complete the button effect on a persons phone.

**Comment by joey-spooner** [comment]
@waltcerna edits/changes
- [x] Dataset nav comp that uses bullets instead of grid format.
- [x] Flush left individual dataset content (location/description) and bold headings.
- [x] Use the same location url background styling as that of production.

**Comment by waltcerna** [comment]
@spoonstein 
Updated files.
![mobile_dev_site_0002_dataset-details](https://cloud.githubusercontent.com/assets/1934400/6925987/513d9dfa-d7b1-11e4-86c1-7b6441d7b1da.jpg)
![mobile_dev_site_0003_datasets dropdown v2](https://cloud.githubusercontent.com/assets/1934400/6925988/579cd2b0-d7b1-11e4-945a-ae6ae2ff4cbc.jpg)

**Comment by joey-spooner** [comment]
@waltcerna changes:
- [x] Dotted line (grey) separator between each dataset (no bullets)
- [x] No grid if more than 6 items, else grid
- [x] Alphabetize the list
- [x] Increase font size (if possible)
- [x] Balance font and icon sizing for dataset groupings
- [x] Include at least a two table listing in an updated layout ( Example: http://developer.dol.gov/health-and-safety/dol-osha-compliance/ )

**Comment by waltcerna** [comment]
@spoonstein How about something like this for the tables selection and reveal? Another option, that I haven't mocked up yet is a drop down selection which iOS shows in a rolodex format, which would make it easier to choose a table. Just a thought. But here are the 2 screens for the detailed page.

## Main screen before selection of table

![dev_site_injuriesillness](https://cloud.githubusercontent.com/assets/1934400/7185352/2baeceb6-e430-11e4-8948-642418a14201.jpg)

## After selection has been made

![dev_site_ii_table](https://cloud.githubusercontent.com/assets/1934400/7185351/2bab0916-e430-11e4-926a-d4a26ae5780c.jpg)

**Comment by joey-spooner** [comment]
@MikePulsiferDOL please review and confirm that you're ready for @neilneyman to break this down into code.

**Comment by MikePulsiferDOL** [comment]
👍🏼

**Comment by adams-lisa** [comment]
Supporting documentation included.  Close
