### ISSUE TITLE
Beginners Page (mobile)

### ISSUE THREAD

**Issue by spoonstein** [USDepartmentofLabor/Developer#25]

**Comment by waltcerna** [comment]
## Beginner Page

![beginner_iphone4 2](https://cloud.githubusercontent.com/assets/1934400/6621946/e8081b9a-c8af-11e4-83e9-df8e5f1e4c95.jpg)

![beginner_dropdown_iphone4 2](https://cloud.githubusercontent.com/assets/1934400/6621952/edcf41a2-c8af-11e4-8f9b-b0e28e6ab2ee.jpg)

**Comment by waltcerna** [comment]
@spoonstein 
## Updated App section

### Main Beginner's page
![mobile_dev_site_0005_beginner main](https://cloud.githubusercontent.com/assets/1934400/6718211/5ccdc240-cd88-11e4-80d1-e9619808d7b1.jpg)

### Beginner's dropdown
![mobile_dev_site_0004_beginner dropdown](https://cloud.githubusercontent.com/assets/1934400/6718210/5ccba62c-cd88-11e4-9621-84c19c6f50b7.jpg)

**Comment by jfc3-dol** [comment]
Really wish Apple and Google would have picked colors that have better or good color contrast.

**Comment by adams-lisa** [comment]
verification & UAT complete. Pushed to v1.0.0
