### ISSUE TITLE
First Data Highlights Page (VETS-100/100A)

### ISSUE THREAD

**Issue by MikePulsiferDOL** [USDepartmentofLabor/Developer#27]
Text:

The U.S. Department of Labor Veterans' Employment and Training Service (VETS) and Office of Federal Contractor Compliance Programs (OFCCP) have supported affirmative actions to employ and advance “covered veterans" in employment since 2008. Contractors and subcontractors who enter into, or modify a contract or subcontract with the federal government, and whose contract meets certain criteria,* are required to report annually on their affirmative action efforts in employing veterans.

This data is a must for anyone interested in the number of veterans employed with companies having contracts with the Federal government.  

You can find out about companies hiring veterans and where they are located. You can also obtain data reflecting the number of veterans working with Federal contractors in several different job categories. Using the VETS-100 and VETS 100A data you and your app’s users can see the numbers of veterans hired who fit into categories including:  

* special disabled
* Vietnam era
* recently separated veterans
* service-medal recipients
* and other protected categories

*= (Sections 4211 and 4212 of title 38 of the U.S. Code, and as set forth at sections 61-250 and 61-300 in title 41 of the Code of Federal Regulations)
![vets-100 data 001](https://cloud.githubusercontent.com/assets/1970829/6674675/d71b1f2c-cbf1-11e4-94f0-2d0e6ffa8c41.png)

**Comment by spoonstein** [comment]
@waltcerna this will replace the CPI block on the homepage. Feel free to update the treatment of that block with some of this information. @neilneyman please use graphics from @waltcerna and incorporate this content into a new folder "highlights/2015/" as "VETS100".

**Comment by MikePulsiferDOL** [comment]
At the end of the content, please include a link to the VETS-100 dataset documentation.

**Comment by waltcerna** [comment]
@neilneyman @spoonstein @MikePulsiferDOL 
Heres the graphic that would go along with the highlight. Please let me know your thoughts/comments/questions/concerns/changes.

![vetgraph](https://cloud.githubusercontent.com/assets/1934400/6716067/2f28c8a8-cd79-11e4-8535-3ebfb0f54818.png)

**Comment by MikePulsiferDOL** [comment]
looks great
