### ISSUE TITLE
Web and Desktop - Was this page helpful - No suffix

### ISSUE THREAD

**Issue by nmangu** [USDepartmentofLabor/Developer#31]
The link to 'Was this page helpful' has no '?' (Question Mark) as suffix.

URL's of the link tested: 
/beginner/
/experienced/

![was_this_page_helpful](https://cloud.githubusercontent.com/assets/10868918/6739527/7cb52b44-ce4f-11e4-9fb0-24bba3fd386b.png)

**Comment by neilneyman** [comment]
This should be fixed now
