### ISSUE TITLE
Mobile Design Complete

### ISSUE THREAD

**Issue by joey-spooner** [USDepartmentofLabor/Developer#37]
Complete all responsive design work for this round of work.

**Comment by waltcerna** [comment]
@spoonstein @MikePulsiferDOL @neilneyman @jfc3-dol @steo-dol
Here is a link to the prototype of the mobile version.
http://marvl.in/6116fi

You can load this up on your phone by typing in the link. You might be able to download the app and look at it through there as well. Not sure. But I do have it on my phone if that doesnt work.

**Comment by joey-spooner** [comment]
Thanks!

**Comment by joey-spooner** [comment]
@MikePulsiferDOL has confirmed the mobile design is complete. We'll start development soon.
