### ISSUE TITLE
Missing documentation for .net SDK

### ISSUE THREAD

**Issue by joey-spooner** [USDepartmentofLabor/Developer#39]
Documentation is missing http://developer.dol.gov/sdk/ for the .net SDK.  Documentation for .net SDK was stored in old site CMS and not via GitHub.

The best backup I can find is here, unless you, @neilneyman , have a db copy still within your development environment.

https://web.archive.org/web/20130625032617/http://developer.dol.gov/sdk-documentation/net-dol-data-sdk

**Comment by MikePulsiferDOL** [comment]
For now, see https://github.com/USDepartmentofLabor/DotNet_DOLDataSDK/issues/3 for the SDK documentation.  

For now, let's remove the links to the Sample app until that can be created in Github.

**Comment by neilneyman** [comment]
I have an export for both the documentation and sample app website.  Do we actually have a sample app somewhere?
