### ISSUE TITLE
Safari Push Notifications

### ISSUE THREAD

**Issue by MikePulsiferDOL** [USDepartmentofLabor/Developer#42]
Add Safari Push Notifications

**Comment by MikePulsiferDOL** [comment]
Dialog isn't coming up.  Take the js code out of the separate file?

**Comment by neilneyman** [comment]
Looks like the javascript is running, without errors, but it's automatically setting the permission to denied.  Checking in the safari developer console, I get 2 logged messages:
- This is a new web service URL and its validity is unknown.
- The user said no.

I found this: https://community.pushwoosh.com/questions/427/permissiondatapermission-denied-without-interaction  but it looks like our javascript closely matches that.   Is there any logging or other information available from their website?

**Comment by MikePulsiferDOL** [comment]
fixed.  Pushwoosh was set up to support two URLs.  I deleted one, leaving developer.dol.gov and the alert now comes up.

http://stackoverflow.com/questions/20036446/safari-push-notifications-return-denied-without-asking
