### ISSUE TITLE
May Data Highlight

### ISSUE THREAD

**Issue by MikePulsiferDOL** [USDepartmentofLabor/Developer#45]
We need to highlight our request for feedback from the public on what datasets they would like to see from DOL.

TEXT:
Four years ago, we released our Labor Department-wide API with the hope that anyone who wants to build an app using our data could do so easily. At the time, we started off with three datasets. Today, we have around 200, including workplace injuries and illnesses, the unemployment rate, companies’ compliance with wage and hour laws, and many other important topics. We hope that the data we publish can help people who have jobs, are looking for jobs, or are even retired from their jobs.

Data has the power to help American businesses compete, succeed and hire more people. It can even spawn an entire industry. A great example is how the [National Weather Service’s data](http://www.commerce.gov/news/blog/2014/10/deputy-secretary-andrews-emphasizes-how-national-weather-service-employees-work) is used by major retailers and the airline industry, among others, to make critical decisions on a daily basis.

If you have an idea for an app that would help you and the public access certain types of information, but don’t see a dataset that you’re looking for, let us know. We are currently working on more data to release, and need to know what is important to you. To tell us what data you want, [create an issue in GitHub](https://github.com/USDepartmentofLabor/DOLAPI/issues) site where we will track all of your requests.

Thanks for taking the time to tell us what you think!

**Comment by neilneyman** [comment]
http://developer.dol.gov/highlights/2015/tell-us-what-data-you-want/
& 
http://developer.dol.gov

b07d1c3f6f53922de06433f2d1c34c2064df8dd3
