### ISSUE TITLE
Minor content edit

### ISSUE THREAD

**Issue by MikePulsiferDOL** [USDepartmentofLabor/Developer#50]
The dataset consists of inspection case detail for approximately 100,000 OSHA inspections conducted annually.

should be...

The dataset consists of inspection case detail for approximately 90,000 OSHA inspections conducted annually.

**Comment by neilneyman** [comment]
@MikePulsiferDOL Does this change apply to both of these datasets?
http://developer.dol.gov/health-and-safety/dol-osha-enforcement/
http://developer.dol.gov/health-and-safety/dol-osha-compliance/

**Comment by MikePulsiferDOL** [comment]
Just the newer one.
