### ISSUE TITLE
Use Quarry for App Add Location on homepage

### ISSUE THREAD

**Issue by joey-spooner** [USDepartmentofLabor/Developer#51]
Title: Quarry

Text: Use the same technology that runs DOL's next generation API.  Turn your databases into a single API with Quarry.

![quarry_sq](https://cloud.githubusercontent.com/assets/225617/8384439/ecbfe098-1c0e-11e5-8045-7b81984718ea.gif)

Button: Grab the Code [link to https://github.com/USDepartmentofLabor/Quarry]

**Comment by joey-spooner** [comment]
Sound good, @MikePulsiferDOL?

**Comment by joey-spooner** [comment]
Note, replaces LaborStats.

**Comment by MikePulsiferDOL** [comment]
👍🏼

(that's a thumbs-up for those of you with less-capable systems :) )

**Comment by neilneyman** [comment]
So we're also using to replace the mobile section that links to the app-stores?    My cool javascript device-detection bit only had a 3-day shelf life.
:octocat:

**Comment by MikePulsiferDOL** [comment]
Temporarily.  It will come back.  Give it 3 weeks.

**Comment by neilneyman** [comment]
This is updated on developerportal dev
