### ISSUE TITLE
Make Dataset names mixed-case

### ISSUE THREAD

**Issue by MikePulsiferDOL** [USDepartmentofLabor/Developer#53]
V1 API is case sensitive with dataset names.  Developer.dol.gov currently displays dataset names as all upper-case.  Using all upper-case in API calls generates 404s.

**Comment by neilneyman** [comment]
@jfc3-dol Did this get changed when you added the mobile datasets?  It looks like earlier versions were correct... eg https://github.com/USDepartmentofLabor/Developer/blob/v2.0.1/health-and-safety/_posts/2013-01-29-basic-mine-info.md

**Comment by MikePulsiferDOL** [comment]
![developerallcaps](https://cloud.githubusercontent.com/assets/1970829/8459150/47e195f6-1fe9-11e5-912a-b5e19d42f457.png)

**Comment by neilneyman** [comment]
I think we also want to reverse this so the caption is the exact match and the title header above is more like the description?  This is what Joey asked me to do on the enforcement page http://developer.dol.gov/health-and-safety/dol-osha-enforcement/

So in the pic mike posted above the corrected version would be:

### Consumer Price Index Table

More Information and details about the data...

consumerPriceIndex

| Column Name | Column Description | Data Type |
| --- | --- | --- |
| year | year - PK | int |
| period | etc | int |

**Comment by MikePulsiferDOL** [comment]
Correct.  Test in browser to make sure it's right.  It's not necessarily consistent in V1.

**Comment by neilneyman** [comment]
Looks like there is simply from a text-transform: uppercase on h3 for the datasets, so this will be fixed in the next push
