### ISSUE TITLE
Skip Navigation and Internal Page Links Not Working in Safari and Chrome

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Developer#58]
While doing some testing realized that the internal anchors on the developer dataset pages moved you down the page, but if using a keyboard would place you back at the top of the page.

After noticing this a friend (Paul J Adam) post on Twitter about a workaround by adding a tab index of negative one. Here is the link to Paul's example page where the first section is the broken version and the second is the correct one with the tab index of negative one added to correct Safari and Chrome issue  - http://pauljadam.com/demos/inpagelinks.html

Below is an example of the necessary code to add:

tabindex="-1"

Have gone in and added the tab index of negative one to all the dataset pages so far where the in-page anchors are. They are connected to the heading level three (h3) tags on those pages, which have the individual ID's on them.

Will assign code update to the tech team to post on DEV server.

Need to check the rest of DEVELOPER website to make sure there are no other places we have the same type of issues.

jfc iii

**Comment by neilneyman** [comment]
These changes are updated on dev

**Comment by jfc3-dol** [comment]
Thanks, have reviewed the updated pages and found a few issues where some other commented out API information caused issues with mobile pages. Also changed the "Summer Jobs" page to have the API URL text wrap when in mobile and not allow the screen scroll left and right.

I have sent you the updated code. So can you please move them to the DEV server hopefully for the last time.

**Comment by neilneyman** [comment]
Latest changes are now updated on dev.

**Comment by jfc3-dol** [comment]
I do not see any of the updated changes on the DEV server.

**Comment by neilneyman** [comment]
Fixed that, now waiting on another update...

**Comment by jfc3-dol** [comment]
While adding the tab index of negative one (tabindex="-1") I found the following other issues and have corrected them. When making changes to dot MD files without a proper environment to check changes first makes these changes easy to miss. 

**Health and Safety**
- Fatal Occupational Injuries - extra horizontal line that was not commented out correctly for mobile version of page 
- Safety and Health - improper heading structure for mobile tables and extra horizontal line when in mobile version of page

**Expanding Growth**
- Quarterly Census Employment and Wage (CEW) - broken in page navigation and extra horizontal line that was not commented out correctly
- Workforce Investment Act - check in page anchors because "Lookup Codes" is not a table so needs to be for both and then missed a closing DIV when making "Lookup Codes" in page link for both mobile and desktop

**Others**
- Summer Jobs Service Beta - need to look into changing the markdown links to HTML links so they wrap when in mobile view.

Can you please move the updated code to the DEV server?

**Comment by neilneyman** [comment]
This is updated on DEV now.

**Comment by jfc3-dol** [comment]
Have reviewed updates and everything are working as expected.

Can you move code to QA so we can run a UAT (User Acceptance Test) on these updates before moving to PROD server and updating GitHub with the new code?

**Comment by neilneyman** [comment]
ok, this is now at developerportalqa

**Comment by jfc3-dol** [comment]
While doing a quick check in QA I notice I forgot to have you place a tab index of negative one ( tabindex="-1" ) in the main content section of the page where the skip navigation anchor is located.

Can we correct that, please?

**Comment by jfc3-dol** [comment]
After looking at the rest of the DEVELOPER website pages I have found the following pages either need to have tab index of negative one ( tabindex="-1" ) for their in-page anchors or for their main skip navigation anchor. 

All pages listed below need to have their skip navigation anchor fix and ones with text after further explain what else on the page needs fixing.
- http://developer.dol.gov/
- http://developer.dol.gov/beginner/
- http://developer.dol.gov/beginners-guide/
- http://developer.dol.gov/accessing-the-apis-using-http-requests/ - in page links for API DOL.gov tab. We might want to look into making page easier to read on mobile devices.
- http://developer.dol.gov/experienced/
- http://developer.dol.gov/highlights/2015/safety-and-transparency/ - the MSHA link at bottom of page is not working.
- http://developerportalqa.opadev.dol.gov/health-and-safety/dol-osha-enforcement/ - the www.osha.gov link has HREF misspelled so the link doesn't work correctly.

Please note some pages may share the same template.

**Comment by neilneyman** [comment]
Those changes are all made on dev.  Note the [explore our data](http://developerportal.opadev.dol.gov/dataset/) and [grab our code](http://developerportalqa.opadev.dol.gov/sdk/) pages are both standalone and used as includes (for example in [Experienced](http://developerportalqa.opadev.dol.gov/experienced/)  (These are all qa site links).   So on beginner and experienced that meant multiple locations of `tabindex="-1"`.  But that doesn't seem to cause any problems.

**Comment by jfc3-dol** [comment]
The following pages still have issues with their mobile versions:
- http://developer.dol.gov/
- http://developer.dol.gov/beginner/
- http://developer.dol.gov/experienced/

The in page anchors  for API DOL.gov tab. We might want to look into making page easier to read on mobile devices.
- http://developer.dol.gov/accessing-the-apis-using-http-requests/

**Comment by jfc3-dol** [comment]
Thanks, for making the necessary updates. I have tested them on the DEV serve and they look great. Now it's on to the QA server to do UAT (User Acceptance Test).

**Comment by adams-lisa** [comment]
Configuration file was updated on this change to reflect updates.

**Comment by jfc3-dol** [comment]
Reviewed the issues listed above and spot checked the dataset pages for the correction in Chrome. Everything looks good, so we can close this issue.

**Comment by adams-lisa** [comment]
QA review complete.   Closed
