### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by vinoo999** [USDepartmentofLabor/Developer#66]
On the [Developer's Beginner's Guide](http://developer.dol.gov/beginners-guide) the link at the bottom referring to HTTP Requests is broken: http://developer.dol.gov/accessing-the-apis-using-http-requests/  
Should instead be without the final forward slash: http://developer.dol.gov/accessing-the-apis-using-http-requests

**Comment by MikePulsiferDOL** [comment]
Thanks.  We've had to make these fixes ever since Github tweaked their back-end.  I'll have someone else look at this before I close it.

**Comment by jfc3-dol** [comment]
Finished testing the two broken links and they work.
