### ISSUE TITLE
Status of WHPS endpoint?

### ISSUE THREAD

**Issue by waldoj** [USDepartmentofLabor/Developer#74]
For [this DOL project at 18F](https://github.com/18F/Paid-Leave-Prototype), it'd be helpful to have API-based access to state minimum wage data. If I properly understand [this Stack Exchange interaction](http://opendata.stackexchange.com/questions/9988/minimum-wage-data-via-dol-api), that endpoint is temporarily down. Am I correct that this is data that is hypothetically offered via the API? If so, is there an ETA on when that will work again?

Thanks!

**Comment by matthenry87** [comment]
Would also like to know when the WHPS endpoint will be working.

Thanks

**Comment by giridhar** [comment]
we are looking into this, Will keep you posted.

**Comment by waldoj** [comment]
Thank you, @giridhar!

**Comment by matthenry87** [comment]
Great thank you so much!

Can you confirm that the WHPS would provide programmatic access to State Minimum Wage data? At a glance it seems to just provide access to Documents and Publications. It would be ideal for my application that I could access State Minimum Wage date without having to scrape it from a document/publication.

Thanks

**Comment by giridhar** [comment]
@waldoj WHPS data should be able to get the data using https://data.dol.gov/get/publications_view. we are in the process of updating the developer.dol.gov site.

**Comment by giridhar** [comment]
Closing this as the website had been updated and the dataset connectivity is working.

**Comment by matthenry87** [comment]
I am unable to use https://data.dol.gov/get/publications_view as I am receiving the 'Invalid API Key' message with 2 separate keys. I added a comment to the other relevant thread about this issue.

Also, I am still not clear if this API will provide programmatic access to State Minimum Wage data. Will this API allow me to automate the process of obtaining the Minimum Wage for each State?
