### ISSUE TITLE
Dead Links to Dataset Download Page

### ISSUE THREAD

**Issue by adevoid** [USDepartmentofLabor/Developer#75]
I am not able to access this link and download the datasets it has on it. I can only view a snapshot of this page from a google cache taken on December 23rd. 
http://ogesdw.dol.gov/views/data_catalogs.php
This link also does not work: 
http://api.dol.gov/V1/Compliance/WHD/

I want to download the Wage and Hour Compliance Action Data, but I can't find a working link anywhere. 

I have been redirected to data.gov, but it does not have this dataset either.

I just saw it the other day.

**Comment by giridhar** [comment]
AFAIK To access the data you need to have the API key to the developer.dol.gov. Once you have the API key you can access the data in the following way. 

`http://api.dol.gov/V1/Compliance/WHD/full?key=1234-5678-90`

you can look at the datasets and how to use the api in the following documents 

`http://developer.dol.gov/beginners-guide`

**Comment by adevoid** [comment]
Thanks, I got an API key and plugged it in and got the XML, however it doesn't seem to have as much information in it as the excel document had that I had downloaded a while ago. Am I doing something wrong? How can I look at all of the compliance data? 

Also how do I follow the below instructions to get it in json? I appreciate your help.

> To receive the data in JSON, send an "Accept" header with "application/json."

**Comment by giridhar** [comment]
Right now the server responds in xml . You may have to depend on libraries that can convert xml to json.

**Comment by neilneyman** [comment]
It will also respond in json.  You need to add the header "Accept: application/json" to your request to get it back as json.     If this is a curl request, for example, use something like:
`curl -H "Accept: application/json" "http://api.dol.gov/V1/Compliance/WHD/full?key=1234-5678-90"`

If you are using a programming language to do this, you may be able to find some examples in the SDKs https://github.com/USDepartmentofLabor?utf8=%E2%9C%93&q=SDK&type=&language=
