### ISSUE TITLE
Mock-up Experienced 2nd Level Page

### ISSUE THREAD

**Issue by MikePulsiferDOL** [USDepartmentofLabor/Developer#8]
Mock-up 2nd Level Page targeted at experienced developers

**Comment by waltcerna** [comment]
@spoonstein edits made and new layout with new menu. 2 options for the GET HELP and API DETAILS section.
![developers_mockup6](https://cloud.githubusercontent.com/assets/1934400/5598830/d4bde106-928a-11e4-98cc-3ce7d7b8814a.jpg)

![developers_mockup7](https://cloud.githubusercontent.com/assets/1934400/5598831/d4bfef14-928a-11e4-9d83-b77daaca9f55.jpg)

**Comment by jfc3-dol** [comment]
The call to action button for the "Developers Guide" section should be bigger to help people notice it, especially, since there is room to do so.

jfc iii

**Comment by jfc3-dol** [comment]
The chosen text under the "Developers Guide" section and other parts of the comps is a bit thin, which can be an issue for ease of reading.

jfc iii

**Comment by jfc3-dol** [comment]
From the second comp, I think we might have to add a bit more contrast to the text in the "API Details" and "Get Help" sections. It might make sense to have the images next to them as background images in the CSS. We would do this so we don't have to worry about ALT for them that would most likely be the same as the text next to them.

jfc iii

jfc iii

**Comment by jfc3-dol** [comment]
In the second comp, we should add a heading to the section with the four images (red cross, chart, etc.). Plus making text below the either bolder or larger so people notice them.

jfc iii

**Comment by jfc3-dol** [comment]
In the second comp, we should maybe break the information out into mobile and tablet information, along with one for web-based application information. 

We will need to add additional text off-screen to differentiate between the different links. There are eight links that say "Git". The best way, to do this, might be for them to start like this:

Android Git
Apple iOS Git 
Ruby Git
etc.

jfc iii

**Comment by jfc3-dol** [comment]
In the second comp, the "Applications that Use Out API" section should have the headings below the images and lists moved above them so people will notice them. It's helpful for screen reader users, since source order matters the way they get the information. If we put the image and list first, people won't know what it's about or why it's there.

jfc iii

**Comment by jfc3-dol** [comment]
One point, we should think about for all these comps, is we should use the template and CSS Shirley has built. Doing this will help us make the pages responsive, along with taking a lot of the guess work out of browser testing, etc.

We might have to make a few overrides to the CSS to get the look we are going for, but it's a great start.

jfc iii

**Comment by teo-siewwah** [comment]
My suggestion:

- IF background color added to the buttons on the CALL OF ACTION on the homepage, I think can add same color background on the header of the DEVELOPERS GUIDE. This clearly show that this page is for that purpose.
- Add brief description for the DIVE INTO OUR DATASET
- Add color on text hyperlinks
