### ISSUE TITLE
Mock-up Beginner 2nd Level Page

### ISSUE THREAD

**Issue by MikePulsiferDOL** [USDepartmentofLabor/Developer#9]
Mock-up 2nd level page targeted at beginning/novice developers or anyone new to web APIs.

**Comment by waltcerna** [comment]
@spoonstein new beginner page with new menu and gradient background on HOW API WORKS Intro section.
![novice5](https://cloud.githubusercontent.com/assets/1934400/5598817/8ba12708-928a-11e4-9e4d-9d624371990e.jpg)

**Comment by jfc3-dol** [comment]
From the second comp the call to action button for the Beginners Guide" section should be bigger to help people notice it, especially since there is room to do so.

jfc iii

**Comment by jfc3-dol** [comment]
From the second comp the chosen text under the "Developers Guide" section and other parts of the comps is a bit thin, which can be an issue for ease of reading.

jfc iii

**Comment by jfc3-dol** [comment]
In the second comp, we should maybe break the information out into mobile and tablet information, along with one for web-based application information.

We will need to add additional text off-screen to differentiate between the different links. There are eight links that say "Git". The best way, to do this, might be for them to start like this:

Android Git
Apple iOS Git
Ruby Git
etc.

jfc iii

**Comment by jfc3-dol** [comment]
In the second comp, the "Applications that Use Out API" section should have the headings below the images and lists moved above them so people will notice them. It's helpful for screen reader users, since source order matters the way they get the information. If we put the image and list first, people won't know what it's about or why it's there.

jfc iii

**Comment by jfc3-dol** [comment]
One point, we should think about for all these comps, is we should use the template and CSS Shirley has built. Doing this will help us make the pages responsive, along with taking a lot of the guess work out of browser testing, etc.

We might have to make a few overrides to the CSS to get the look we are going for, but it's a great start.

jfc iii

**Comment by teo-siewwah** [comment]
My suggestion:

- IF background color added to the buttons on the CALL OF ACTION on the homepage, I think can add same color background on the header of the BEGINNERS GUIDE. This clearly show that this page is for that purpose.
- Add brief description for the DIVE INTO OUR DATASET
- Add color on text hypelinks so differentiate on other static text.
- Add brief description for the APPLICATIONS THAT USE OUR API
