### ISSUE TITLE
Sweat and Toil, no easy way to pull the data

### ISSUE THREAD

**Issue by tinglesby87** [USDepartmentofLabor/Developer#91]
The directions to pull tables on the site does not work with either of the Sweat and Toil data table sections.  This is exceedingly difficult, if not impossible.  It would be helpful if you provided more explicit directions on your website on how to pull the data for those sections.  Or take it off the website and stop promoting that that data is accessible if it is not.

**Comment by giridhar** [comment]
@tinglesby87 It appears to be an issue connecting to the dataset. we will take a look and fix this.

**Comment by giridhar** [comment]
The dataset issue has been addressed. Please try `curl -k -H "X-API-KEY: yourkey" https://quarry.dol.gov/get/SweatToilAllCountries/format/json/limit/10`
